# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios-blue-tool-box' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SideMenu', '~> 6.0'
  pod 'Charts'

  # Pods for ios-blue-tool-box

  target 'ios-blue-tool-boxTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'SideMenu', '~> 6.0'
    pod 'Charts'
  end

end
